### ISSUE TITLE
not able to compile a sample program using "-mcpu=em_mini" with arc-elf32-gcc from command line

### ISSUE THREAD

**Issue by joejohnpaulines** [foss-for-synopsys-dwc-arc-processors/toolchain#216] opened 2019-12-10 13:44 UTC
I am not able to compile a sample code using "arc-elf32-gcc -mcpu=em_mini -g hello.c" and I am getting below error.
```
#include <stdio.h>

int main(void)
{
  printf("Hello World from nSIM!\n");
  return 0;
}
```

```
> ERROR: 
> /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/bin/ld: error: a.out: cannot mix rf16 with full register set /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/em_mini/libgcc.a(_mulsi3.o)
> /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/bin/ld: failed to merge target specific data of file /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/em_mini/libgcc.a(_mulsi3.o)
> /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/bin/ld: error: a.out: cannot mix rf16 with full register set /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/em_mini/libgcc.a(_divsi3.o)
> /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/bin/ld: failed to merge target specific data of file /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/em_mini/libgcc.a(_divsi3.o)
> /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/bin/ld: error: a.out: cannot mix rf16 with full register set /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/em_mini/libgcc.a(_divmod_tools.o)
> /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/bin/ld: failed to merge target specific data of file /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/em_mini/libgcc.a(_divmod_tools.o)
> /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/bin/ld: error: a.out: cannot mix rf16 with full register set /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/em_mini/crtn.o
> /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/bin/ld: failed to merge target specific data of file /SCRATCH/Joe/GNU_19_12/arc_gnu_2019.09-rc2_ide_linux_install/bin/../lib/gcc/arc-elf32/9.2.1/em_mini/crtn.o
> collect2: error: ld returned 1 exit status
```

here i used arc-elf32-gcc from the GNU ide's bin folder [ arc_gnu_2019.09-rc2_ide_linux_install/bin/arc-elf32-gcc].

Environment Details :

Os : Centos 7.3
GNU : 2019.09-RC2

Thanks,
Joe

**Comment by abrodkin** [comment] 2019-12-10 15:17
@claziss could you please look into this one? Looks like libgcc and C-runtime for `-mcpu=em_mini` are compiled in assumption of existence of full register file.

**Comment by abrodkin** [comment] 2019-12-10 15:18
@joejohnpaulines the same is reproduced with `arc-2019.03` so this is not a regression but instead something pretty old. Let's see what Claudiu says.

**Comment by claziss** [comment] 2019-12-10 18:40
The issue is located in the assembly only files of libgcc which are compiled to default no-rf16 architecture. See:
```
ibgcc.a(_mulsi3.o)
Attribute Section: ARC
File Attributes
  Tag_ARC_CPU_base: ARCEM
  Tag_ARC_CPU_name: "arcem"
  Tag_ARC_ABI_osver: v4
  Tag_ARC_ATR_version: 1
```
The c-files are compiled accordingly:
```
libgcc.a(_ashrdi3.o)
Attribute Section: ARC
File Attributes
  Tag_ARC_PCS_config: Bare metal/newlib
  Tag_ARC_CPU_base: ARCEM
  Tag_ARC_CPU_variation: Core2
  Tag_ARC_CPU_name: "arcem"
  Tag_ARC_ABI_rf16: yes
  Tag_ARC_ABI_osver: v4
  Tag_ARC_ABI_sda: GNU
  Tag_ARC_ATR_version: 1
```

**Comment by claziss** [comment] 2019-12-11 11:08
I have qualified the hand-made assembly files present in libgcc in this patch:
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/719202defb9775a7b9bee59b19f8038a17757f3f

I need to double check if newlib is ok as well.

**Comment by claziss** [comment] 2019-12-11 11:19
It seems newlib is also ok. The commit 95d524de494aa4bdd8a52855ff2275ef40dc022e takes care of it.

**Comment by abrodkin** [comment] 2019-12-11 11:57
> 
> 
> It seems newlib is also ok. The commit 95d524de494aa4bdd8a52855ff2275ef40dc022e takes care of it.

Could you please paste full URL to this commit as otherwise it's not clear where this commit is supposed to be. There's nothing with such hash in ARC GCC repo.

**Comment by claziss** [comment] 2019-12-11 12:34
https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/637f118ae89b3de54d693595481838f076ea8d9b

**Comment by abrodkin** [comment] 2019-12-16 08:09
The fix now in arc-2019.09-rc2 and proven to work!

**Comment by abrodkin** [comment] 2019-12-19 10:01
Well there seem to be yet another fall-out:
```
$ cat hello.c
#include <stdio.h>

int main(void)
{
        printf("Hello world!\n\r");
        return 0;
}

$ arc-elf32-gcc -mcpu=em_mini hello.c
.../2019.09-rc3/elf32_le_linux/bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/bin/ld: error: a.out: cannot mix rf16 with full register set .../2019.09-rc3/elf32_le_linux/bin/../lib/gcc/arc-elf32/9.2.1/em_mini/libgcc.a(_umodsi3.o)
.../2019.09-rc3/elf32_le_linux/bin/../lib/gcc/arc-elf32/9.2.1/../../../../arc-elf32/bin/ld: failed to merge target specific data of file .../2019.09-rc3/elf32_le_linux/bin/../lib/gcc/arc-elf32/9.2.1/em_mini/libgcc.a(_umodsi3.o)
collect2: error: ld returned 1 exit status
```

@claziss could you please take a look at what's wrong with `_umodsi3`?

@joejohnpaulines for the record I was not able to reproduce this problem just because I didn't use "carriage return" symbol (`\r`) in my example. I.e. the following code gets built normally:
```
printf("Hello world!\n");
```
but with added `\r` it fails as you saw:
```
printf("Hello world!\n\r");
```

**Comment by abrodkin** [comment] 2019-12-20 14:50
Finally fixed with https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/f792d846612417bbdcc350715c982c671a9dda28.

**Closed as completed by abrodkin** 2019-12-20 14:50 UTC
Labels: bug, component: gcc
