### ISSUE TITLE
ARCv2: glibc tests for the trunc() function fail with ARC2022.09 gcc

### ISSUE THREAD

**Issue by pavelvkozlov** [foss-for-synopsys-dwc-arc-processors/toolchain#503] opened 2023-01-09 13:07 UTC
Tests for the glibc implementation of ```trunc()``` function (math/test-double-trunc, math/test-float32x-trunc, etc) fail with the ARC2022.09 gcc and pass with the previous ARC2022.03 gcc.

The latest gcc for ARCv2 generates code that cause inaccurate ```trunc()``` function result when max value for the float/double type is passed as an argument.
The issue occurs with -O2 optimization. With -O1 optimization level the ```tunc()``` function returns expected result.
Also, the ```-O1``` optimization level with additional ```-fcse-follow-jumps -fgcse -frerun-cse-after-loop``` flags also cause this issue.
A small test based on the implementation of the ```trunc()``` function from glibc, that reproduces this issue: [math-trunc.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/10373344/math-trunc.zip)

**Comment by abrodkin** [comment] 2023-01-11 11:47
@claziss do we want to have that addressed in `arc-2022.09`? If so let's try to do it quickly so that we may cut RC2 soonish.
Otherwise, if it's not critical, maybe we postpone it till say `arc-2023.03`.

**Comment by claziss** [comment] 2023-01-12 11:13
@pavelvkozlov  Please can you confirm:

```
Math trunc test started.
Trunc result:      1.797692277655430159e+308 (0x7fefffff00000000)
Should be:         1.797693134862315708e+308 (0x7fefffffffffffff)
FAIL
```

**Comment by pavelvkozlov** [comment] 2023-01-12 11:47
Yes, that is what I see too and what I reported about. It is output of my small test. 
The output from glibc tests (for example math/test-double-trunc) looks like:
```
testing double (without inline functions)
Failure: Test: trunc (max_value)
Result:
 is:          1.7976922776554302e+308   0x1.fffff00000000p+1023
 should be:   1.7976931348623157e+308   0x1.fffffffffffffp+1023
 difference:  8.5720688554942983e+301   0x1.fffffffe00000p+1002
 ulp       :  4294967295.0000
 max.ulp   :  0.0000
Failure: Test: trunc (-max_value)
Result:
 is:         -1.7976922776554302e+308  -0x1.fffff00000000p+1023
 should be:  -1.7976931348623157e+308  -0x1.fffffffffffffp+1023
 difference:  8.5720688554942983e+301   0x1.fffffffe00000p+1002
 ulp       :  4294967295.0000
 max.ulp   :  0.0000
```

**Comment by claziss** [comment] 2023-01-12 12:40
@pavelvkozlov  please use `-fno-tree-forwprop` until further developments.  It may be a mainline issue.
@abrodkin you can cut `2022.09`.

**Comment by BrunoASMauricio** [comment] 2023-05-04 14:46
Same problem as in issue https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/531
Details copied over from closed issue:
### Description of the problem
When using the -O2 flag, gcc isn't preserving one of the two return registers (r0, r1) required when returning a double value from a function.

In the following example (couldnt be made smaller otherwise the outcome was different) we have two binaries, "none" on the left and "o2" on the right, compiled with no optimization flag and -O2 respectively:

Input to custom `double trunc(double)` function:

![image](https://user-images.githubusercontent.com/113055161/235884934-75165011-0628-45b6-bb70-506797f40c4a.png)

Output:

![image](https://user-images.githubusercontent.com/113055161/235885184-2592b8f8-4408-4ce7-9f65-c9d43a365e10.png)

As we can see, after the call to trunc and right before the call to printf, the values in r0 and r1 are different between the two binaries. This is because in "o2",  r0 isn't restored inside trunc after clobbering:

![image](https://user-images.githubusercontent.com/113055161/235885629-88483e0d-536f-45e1-aec2-50100c1d747f.png)

Restoration or r0 and r1 at `0x3a8` and `0x3aa` for "none" but nothing for "o2", even though r0 is clobbered at `0x28c <trunc+28>        neg.f   r0,r14`

### How to reproduce:

Use the attached [trunc.c.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/files/11381465/trunc.c.txt) (rename to trunc.c)

```
$ arc-elf32-gcc -mcpu=archs trunc.c -fno-inline -g3 -fno-builtin -o none
$ arc-elf32-gcc -mcpu=archs trunc.c -fno-inline -g3 -fno-builtin -O2 -o o2

And in separate shells, using the latest QEMU:

$ qemu qystem-arc -S -gdb tcp::1234 -M arc-sim -m 3G -nographic -no-reboot -serial stdio -monitor none -display none -cpu archs -kernel ./o2
$ qemu qystem-arc -S -gdb tcp::4321 -M arc-sim -m 3G -nographic -no-reboot -serial stdio -monitor none -display none -cpu archs -kernel ./none
```

Launch GDB and run something similar to

```
(gdb) target remote :1234 OR :4321
(gdb) b trunc
(gdb) la asm
(gdb) set disassembler-options cpu=hs38_linux
(gdb) c
(gdb) fin
(gdb) i r r1 r0
```

**Comment by claziss** [comment] 2023-05-08 08:14
@BrunoASMauricio issue #531 is different from this issue.

**Comment by BrunoASMauricio** [comment] 2023-05-11 08:18
I can confirm that with fpuV2 support and the fixed encodings in QEMU, the patch https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/c928b26e0006a47cb3aca1c9bfbb8bffd365f0ab for issue #531 also fixes this issue (tests math/test-float32x-trunc and math/test-double-trunc pass).
```
PASS: math/test-double-trunc
original exit status 0
testing double (without inline functions)

Test suite completed:
  260 test cases plus 256 tests for exception flags and
    256 tests for errno executed.
  All tests passed successfully.
```
```
PASS: math/test-float32x-trunc
original exit status 0
testing _Float32x (without inline functions)

Test suite completed:
  260 test cases plus 256 tests for exception flags and
    256 tests for errno executed.
  All tests passed successfully.
```

 @pavelvkozlov please validate if the binutils patch solves this in NSIM as well.

**Comment by pavelvkozlov** [comment] 2023-05-12 16:10
I also confirm that https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/c928b26e0006a47cb3aca1c9bfbb8bffd365f0ab fixes initial issue. I've checked on nSIM and HSDK, ```math/test-*-trunc``` fails have gone. 
I hope this binutils fix will be in upstream too. And next time we could show better results with glibc tests: https://sourceware.org/glibc/wiki/Release/2.37#ARC. (here we have to use upstream tools).

**Closed as completed** 2023-07-10 14:12 UTC
Labels: bug, component: gcc
