### ISSUE TITLE
[arc64] atomic builtins missing

### ISSUE THREAD

**Issue by evgeniy-paltsev** [foss-for-synopsys-dwc-arc-processors/toolchain#278] opened 2020-06-17 12:28 UTC
When I build any code with atomic builtins (i.e: `__atomic_fetch_and`) for ARC64 I get following error:
```
/home/xxx/x-tools/arc64-unknown-elf/lib/gcc/arc64-unknown-elf/10.0.0/../../../../arc64-unknown-elf/bin/ld: /tmp/ccO8wxyD.o: in function `main':
lib-check.c:(.text+0x2c): undefined reference to `__atomic_fetch_and_4'
/home/xxx/x-tools/arc64-unknown-elf/lib/gcc/arc64-unknown-elf/10.0.0/../../../../arc64-unknown-elf/bin/ld: lib-check.c:(.text+0x2c): undefined reference to `__atomic_fetch_and_4'
collect2: error: ld returned 1 exit status
```

Do we need to pass some specific options to ARC64 compiler to use it?
ARCv2 compiler builds same code without any issues.

How-to reproduce: ([lib-check.c can be found here](https://gist.github.com/Palmyr3/92f12e08c06d909222079ef133836300))
```
arc64-unknown-elf-gcc lib-check.c
```

**Comment by claziss** [comment] 2020-06-17 13:07
Atomic operations are not added just yet.
Thanks!

**Comment by abrodkin** [comment] 2020-06-17 13:19
@claziss is there any ETA for atomic ops for ARC64?
@Palmyr3 in Zephyr at least I think we may switch to generic atomics implemented in C for now, see `CONFIG_ATOMIC_OPERATIONS_C` (https://elixir.bootlin.com/zephyr/latest/source/kernel/Kconfig#L393).

**Comment by claziss** [comment] 2020-06-17 13:25
First we need to get Linux issues flushed out :) I'll update jira with my estimates asap.

**Comment by claziss** [comment] 2020-08-04 06:54
Closing it, duplicate of #289

**Closed by claziss** 2020-08-04 06:54 UTC
Labels: arc64, component: gcc, enhancement
