### ISSUE TITLE
objdump crashes when using reuse of opcodes

### ISSUE THREAD

**Issue by bravindr** [foss-for-synopsys-dwc-arc-processors/toolchain#87] opened 2016-09-09 22:47 UTC
In the following configuration, objdump crashes.

testcode.s

``` C
 .extInstruction abcd, 7, 0x21, SUFFIX_NONE, SYNTAX_3OP
        .extInstruction efgh, 7, 0x20, SUFFIX_NONE, SYNTAX_2OP
        .extInstruction abab, 7, 0x21, SUFFIX_NONE, SYNTAX_2OP

        .section .text
        .global __start
__start:
      mov r1,0x0
      mov r2,0x1
      mov r3,0x100

      abcd r1,r2,r3
      efgh r2,r3
      swi
```

arc-elf32-gcc -mcpu=arcem -nostdlib testcode.s
arc-elf32-objdump -d a.out

throws this error.

a.out:     file format elf32-littlearc

Disassembly of section .text:

00000100 <__start>:
 100:   214a 0000               mov     r1,0
 104:   224a 0040               mov     r2,0x1
 108:   238a 0004               mov     r3,256
arc-elf32-objdump: /home/akolesov/pub/jenkins_root/akolesov-lab/workspace/gnu_release/binutils/opcodes/arc-dis.c:473: print_insn_arc: Assertion `opcode != ((void *)0)' failed.
 10c:   Aborted

It seems like the issue is related to duplicate sub-opcode (0x21). However, as the two different instruction extensions have different opcode counts, this should be a valid case.

**Comment by fbedard** [comment] 2016-09-09 23:07
what version of the toolchain are you using?

**Comment by bravindr** [comment] 2016-09-09 23:47
arc_gnu_2016.03_prebuilt_elf32_le_linux_install/bin/arc-elf32-objdump  --version
GNU objdump (ARCompact/ARCv2 ISA elf32 toolchain 2016.03) 2.26.51.20160308

**Comment by claziss** [comment] 2016-09-13 09:26
Hi,
Using the latest binutils (2.27.51.20160830) there will be no crash, and the output disassembled code looks like this:

``` asm
00000000 <__start>:
   0:   214a 0000               mov     r1,0
   4:   224a 0040               mov     r2,0x1
   8:   238a 0004               mov     r3,256
   c:   3a21 00c1               .long 0x3a2100c1
  10:   3a2f 00e0               efgh    r2,r3
  14:   3b2f 0121               abab    r3,r4
  18:   226f 003f               swi
```

**Comment by claziss** [comment] 2016-09-13 10:25
The issue is in how you defined the extended instructions. Your definitions actually tell we have two instructions which are having different name and semantics, but they share the same opcode. Hence, the disassembler is confused because it cannot determine which format to use when disassembling. 

The assembler accepts this syntax for cases when the first argument is not used or implied. For example, the _mul64_ operation present in the original ARCompact ISA:

``` asm
    .extInstruction mul64 , 0x05, 0x04, SUFFIX_COND, SYNTAX_2OP|OP1_IMM_IMPLIED
    .extInstruction mul64 , 0x05, 0x04, SUFFIX_COND, SYNTAX_3OP|OP1_MUST_BE_IMM

start:
    mul64   0,r0,r1
    mul64   r2,r4
```

So, in this case the assembler will accept both variants (i.e., 2op and 3op) for mul64 without complaining. However, you need to be careful and place the longer syntax version after the short one because this is how the assembler works internally. Even in this case the disassembler will not know which version to use and will always use the longer one, which is correct, as the above example is just syntactic sugar.

 As for the given example, I think it is either wrong or I do not really understand what you try to do. If you write the asm code like this:

``` asm
    .cpu EM
    .extInstruction abab, 7, 0x21, SUFFIX_NONE, SYNTAX_2OP|OP1_IMM_IMPLIED
    .extInstruction abcd, 7, 0x21, SUFFIX_NONE, SYNTAX_3OP
    .extInstruction efgh, 7, 0x20, SUFFIX_NONE, SYNTAX_2OP

    .section .text
    .global __start
__start:
    mov r1,0x0
    mov r2,0x1
    mov r3,0x100

    abcd r1,r2,r3
    efgh r2,r3
    abab r3,r4
    swi
```

You will observe the disassembler will use _abcd_ mnemonic for both _abcd_ and _adab_, as both instructions are equivalent (or this is my understanding when someone uses the same encoding for two different mnemonics):

``` asm
00000000 <__start>:
   0:   214a 0000               mov     r1,0
   4:   224a 0040               mov     r2,0x1
   8:   238a 0004               mov     r3,256
   c:   3a21 00c1               abcd    r1,r2,r3
  10:   3a2f 00e0               efgh    r2,r3
  14:   3b21 013e               abcd    0,r3,r4
  18:   226f 003f               swi
```

I will close this star as I cannot see any crash or bad behavior.

**Comment by claziss** [comment] 2016-09-13 12:08
I misunderstood the issue.  It is about extension instructions having i-filed set to 0x2f. Reopen.

**Comment by bravindr** [comment] 2016-09-14 22:57
I feel that this about the opcode reuse for 2 operand and 3 operand instructions. As you have noticed, the sub-opcode is inherent in 2 operand case

**Comment by claziss** [comment] 2016-09-15 07:46
The issue is how the extension instructions are match by the disassembler. For each MAJOR-MINOR opcode tuple, we can have either a 3-operand, or 2-operand, or a single operand instruction format, depending on the values present in i-field, and a-field.
The disassembler is reading the section containing the extension instruction format and stores them in a table. Each table element represents a linked list with encodings for a particular MAJOR-MINOR tuple. The issue is the current implementation checks only against the first element of the list, hence, the issue.
I have a patch under testing at this moment which fixes this problem. I need to craft more test cases and validate it. 
N.B. There is a slight nonalignment in the ISA documentation and assembler terminology. The ISA doc calls the assembler's 3-operand instruction as 32-bit instruction format, the assembler's 2-operand instruction is called single operand extension instruction, and the assembler's 1-operand instruciton as zero operand instruction.

**Comment by claziss** [comment] 2016-09-15 10:31
Patch + test proposed here:
https://sourceware.org/ml/binutils/2016-09/msg00104.html

**Comment by claziss** [comment] 2016-09-16 12:57
Patch accepted and pushed:
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=f807f43d7eba5bba3042554f9b3e884d71a68309

**Closed as completed by claziss** 2016-09-16 12:57 UTC
Labels: bug
