### ISSUE TITLE
ARC64/glibc/dlopen lazy binding is not actually lazy

### ISSUE THREAD

**Issue by VVIsaev** [foss-for-synopsys-dwc-arc-processors/toolchain#334] opened 2021-02-25 07:07 UTC
Consider following shared lib and app which is trying to dlopen() it:
lib.c:
```c
extern int foo ();
int unused ()
{
  return foo ();
}
```
main.c:
```c
#include <dlfcn.h>
#include <stdio.h>

int main ()
{
  void *d = dlopen ("lib.so", RTLD_LAZY);

  if (d == NULL)
    {
      fprintf (stderr, "FAIL %s\n", dlerror ());
      return 1;
    }

  fprintf (stderr, "PASS\n");
  return 0;
}
```

If we will try to build and run app:
```
$ arc64-snps-linux-gnu-gcc -fPIC -shared lib.c -o lib.so
$ arc64-snps-linux-gnu-gcc -ldl main.c -o main
$ ssh qemu-arc64
# LD_LIBRARY_PATH=. ./main
FAIL ./lib.so: undefined symbol: foo
```

When expected result is (for example how it works on my host machine):
```
$ gcc -fPIC -shared lib.c -o lib.so
$ gcc -ldl main.c -o main
$ LD_LIBRARY_PATH=. ./main
PASS
```

So `RTLD_LAZY` doesn't work properly.

Here is relocation for foo():
```
$ arc64-snps-linux-gnu-readelf -r ./lib.so | grep foo
000000003ff0  000600000036 R_ARC_GLOB_DAT    0000000000000000 foo + 0
```

For arc32 relocation is R_ARC_JMP_SLOT.

**Comment by claziss** [comment] 2021-02-25 09:39
We introduced in ARC64 a new concept called `memory models` which allows a user to select how the compiler will access data/call functions efficiently for a given model.
In the case of `linux` toolchain, the default one is `medium` memory model, which is using GOT table to locate functions symbol addresses. Hence, the relocation observed by you.
However, if you would like to use the PLT table instead, you can pass to the compiler `-mcmodel=small` to get it.

**Comment by cupertinomiranda** [comment] 2021-02-25 15:53
Vladimir, by Claudiu reply the proposed presented relocation might just be correct.
Can you tell some more why you think that relocation is the problem ?

Please execute the example with LD_DEBUG=all to try to figure out if the relocation gets to be resolved correctly.

**Comment by VVIsaev** [comment] 2021-02-25 16:15
I don't think that relocation is the problem here, it is just difference which I noticed. If such relocation is expected, I think we should process it in glibc, because as I can see from https://github.com/foss-for-synopsys-dwc-arc-processors/glibc/blob/5754a6aa79d8e990cdabcc3baffa454e1e666677/sysdeps/arc/dl-machine.h#L381 we do not expect such relocation to be lazy.

Example with LD_DEBUG=all:

```
...
      1551:
      1551:     transferring control: ./main
      1551:
      1551:     symbol=dlopen;  lookup in file=./main [0]
      1551:     symbol=dlopen;  lookup in file=/lib/libdl.so.2 [0]
      1551:     binding file ./main [0] to /lib/libdl.so.2 [0]: normal symbol `dlopen' [GLIBC_2.32]
      1551:
      1551:     file=lib.so [0];  dynamically loaded by ./main [0]
      1551:     find library=lib.so [0]; searching
      1551:      search path=./tls:.            (LD_LIBRARY_PATH)
      1551:       trying file=./tls/lib.so
      1551:       trying file=./lib.so
      1551:
      1551:     file=lib.so [0];  generating link map
      1551:       dynamic: 0x000000002013be28  base: 0x0000000020138000   size: 0x0000000000004030
      1551:         entry: 0x0000000020138440  phdr: 0x0000000020138040  phnum:                  5
      1551:
      1551:     checking for version `GLIBC_2.32' in file /lib/libc.so.6 [0] required by file ./lib.so [0]
      1551:     object=./lib.so [0]
      1551:      scope 0: ./main /lib/libdl.so.2 /lib/libc.so.6 /lib/ld-linux-arc64.so.2
      1551:      scope 1: ./lib.so /lib/libc.so.6 /lib/ld-linux-arc64.so.2
      1551:
      1551:
      1551:     relocation processing: ./lib.so (lazy)
      1551:     symbol=_ITM_deregisterTMCloneTable;  lookup in file=./main [0]
      1551:     symbol=_ITM_deregisterTMCloneTable;  lookup in file=/lib/libdl.so.2 [0]
      1551:     symbol=_ITM_deregisterTMCloneTable;  lookup in file=/lib/libc.so.6 [0]
      1551:     symbol=_ITM_deregisterTMCloneTable;  lookup in file=/lib/ld-linux-arc64.so.2 [0]
      1551:     symbol=_ITM_deregisterTMCloneTable;  lookup in file=./lib.so [0]
      1551:     symbol=_ITM_deregisterTMCloneTable;  lookup in file=/lib/libc.so.6 [0]
      1551:     symbol=_ITM_deregisterTMCloneTable;  lookup in file=/lib/ld-linux-arc64.so.2 [0]
      1551:     symbol=_ITM_registerTMCloneTable;  lookup in file=./main [0]
      1551:     symbol=_ITM_registerTMCloneTable;  lookup in file=/lib/libdl.so.2 [0]
      1551:     symbol=_ITM_registerTMCloneTable;  lookup in file=/lib/libc.so.6 [0]
      1551:     symbol=_ITM_registerTMCloneTable;  lookup in file=/lib/ld-linux-arc64.so.2 [0]
      1551:     symbol=_ITM_registerTMCloneTable;  lookup in file=./lib.so [0]
      1551:     symbol=_ITM_registerTMCloneTable;  lookup in file=/lib/libc.so.6 [0]
      1551:     symbol=_ITM_registerTMCloneTable;  lookup in file=/lib/ld-linux-arc64.so.2 [0]
      1551:     symbol=__cxa_finalize;  lookup in file=./main [0]
      1551:     symbol=__cxa_finalize;  lookup in file=/lib/libdl.so.2 [0]
      1551:     symbol=__cxa_finalize;  lookup in file=/lib/libc.so.6 [0]
      1551:     binding file ./lib.so [0] to /lib/libc.so.6 [0]: normal symbol `__cxa_finalize' [GLIBC_2.32]
      1551:     symbol=foo;  lookup in file=./main [0]
      1551:     symbol=foo;  lookup in file=/lib/libdl.so.2 [0]
      1551:     symbol=foo;  lookup in file=/lib/libc.so.6 [0]
      1551:     symbol=foo;  lookup in file=/lib/ld-linux-arc64.so.2 [0]
      1551:     symbol=foo;  lookup in file=./lib.so [0]
      1551:     symbol=foo;  lookup in file=/lib/libc.so.6 [0]
      1551:     symbol=foo;  lookup in file=/lib/ld-linux-arc64.so.2 [0]
      1551:     ./lib.so: error: symbol lookup error: undefined symbol: foo (fatal)
...
FAIL ./lib.so: undefined symbol: foo
```

**Comment by vineetgarc** [comment] 2021-02-25 21:14
Note that the symbol @foo is undefined in dso - and since dlopen of the dso is RTLD_LAZY  it not being there should not err out since it is not explicitly called. RTLD_NOW however would try to resolve everything ahead of time and will print the "undefined symbol: foo" msg. On ARCv2 we get exactly the right behavior

```
# LD_LIBRARY_PATH=. ./main-lazy                    <-- dlopen ("lib.so", RTLD_LAZY);
PASS

# LD_LIBRARY_PATH=. ./main-now                     <-- dlopen ("lib.so", RTLD_NOW);
FAIL ./lib.so: undefined symbol: foo 
```
However on ARCv3 RTLD_LAZY is failing which is exactly this issue.

**Comment by vineetgarc** [comment] 2021-02-25 21:22
And as @VVIsaev alludes to as well the issue is because undefined @foo has a GOT relocation inARC64. GOT relocation are always resolved ahead of time.
In ARCv2 however foo is has a PLT relaxation which can be resolved lazy. So this is something to fix in binutils.

**Comment by vineetgarc** [comment] 2021-02-25 21:25
Now to Claudiu's point, indeed with **-mcmodel=small**, we get the PLT relocation 

```
Relocation section '.rela.plt' at offset 0x3e8 contains 2 entries:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000004018  000600000037 R_ARC_JMP_SLOT    0000000000000000 foo + 0
```

But that's not the solution because 
1. We can't build linux libs with small memory model
2. And why would the memory model change convert something from a PLT entry to a GOT entry (function call vs. data symbol). So something in gcc / binutils needs to change.

**Comment by claziss** [comment] 2021-02-26 07:59
The `small` memory model emulates (somehow) how ARCv2 works, while `medium` model has features from `-mlong-calls`. As ARC64 has a large addressing space, I've turned on the `medium` by default. However, if you would like to have PLT access also in `medium` memory model, I can use `ARC_PLT32` or, better, I should introduce a new `PLT64` reloc. But this takes time :)

**Comment by cupertinomiranda** [comment] 2021-02-26 10:45
oTo me this issue needs a solution in the compiler somehow.
@VVIsaev Can you provide pre-processed .i files such that we can investigate how foo is defined and what is being incorrectly done ?

**Comment by abrodkin** [comment] 2021-02-26 10:47
@cupertinomiranda source of the simplest test-case as well as instructions on how to compile are all in the initial report, care to add `--save-temps` to the command line and you'll get what you ask for ;)

**Comment by cupertinomiranda** [comment] 2021-02-26 11:04
Take this as a warning for future bug issues.
They should come with the --save-temps included not instructions how to get them. God knows if you don't have a bad toolchain.

**Comment by cupertinomiranda** [comment] 2021-02-26 11:06
For this one I am still waiting for the .i .s and stuff to be publish in this issue.

**Comment by cupertinomiranda** [comment] 2021-02-26 11:34
It is unclear to me why we need to be placing functions in PLT in the first place.
Also in case you place functions in PLT there is no actual difference in between RTLD_LAZY and RTLD_NOW, and for this reason the test itself looks at least a little "stupid".
The conclusion to take might be: We either are not differentiating Variable from Function symbols properly in the binary, or there is some problem in the dynamic loader that is not differentiating between Variable and Function symbols when resolving them.

I pasted the definitions from the man pages of RTLD_LAZY and RTLD_NOW for reference.

```
       RTLD_LAZY
              Perform  lazy  binding.   Resolve symbols only as the code that references them is executed.  If the symbol is never referenced, then it is never resolved.  (Lazy binding is performed only for function references; references to variables are always immediately bound when the shared object is loaded.)  Since glibc 2.1.1, this flag is overridden by the effect of the LD_BIND_NOW  environment variable.

       RTLD_NOW
              If  this value is specified, or the environment variable LD_BIND_NOW is set to a nonempty string, all undefined symbols in the shared object are resolved before dlopen() returns.  If this cannot be done, an error is returned.
```

**Comment by VVIsaev** [comment] 2021-02-26 11:38
Let me explain the issue here.
`foo()` is not defined, so in case of usual linking we should have this `undefined symbol` error.

But there is a flag `RTDL_LAZY` for `dlopen()`, which should perform lazy binding. From [man dlopen](https://man7.org/linux/man-pages/man3/dlopen.3.html):
```
       RTLD_LAZY
              Perform lazy binding.  Resolve symbols only as the code
              that references them is executed.  If the symbol is never
              referenced, then it is never resolved.  (Lazy binding is
              performed only for function references; references to
              variables are always immediately bound when the shared
              object is loaded.)  Since glibc 2.1.1, this flag is
              overridden by the effect of the LD_BIND_NOW environment
              variable.
```

For example how it works for host gcc:
```
isaev@isaev-7410:tmp$ gcc -fPIC -shared lib.c -o lib.so
isaev@isaev-7410:tmp$ gcc -ldl main.c -o main
isaev@isaev-7410:tmp$ LD_LIBRARY_PATH=. ./main
PASS
```

There is also code in glibc which do this lazy binding, see https://github.com/foss-for-synopsys-dwc-arc-processors/glibc/blob/5754a6aa79d8e990cdabcc3baffa454e1e666677/sysdeps/arc/dl-machine.h#L128 and https://github.com/foss-for-synopsys-dwc-arc-processors/glibc/blob/5754a6aa79d8e990cdabcc3baffa454e1e666677/sysdeps/arc/dl-machine.h#L381 . I don't have understanding about how this actually works internally, but for developer point of view we should perform lazy binding if we provide lazy flag. Not sure where it should be fixed in binutils or in glibc.

If you don't like my test, please use this one: https://github.com/foss-for-synopsys-dwc-arc-processors/glibc/blob/arc64/elf/resolvfail.c . Currently it fails for ARC64 with `cannot load testobj1.so: undefined symbol foo`.

**Comment by VVIsaev** [comment] 2021-02-26 11:43
I don't know how to attach such files to the issue, so please find zip archive: [temp-files.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6049382/temp-files.zip)

**Comment by cupertinomiranda** [comment] 2021-02-26 12:08
By doing : `objdump -t lib.so` you can clearly see that the unused symbol is marked as a function:
```
00000000000004ec g     F .text  0000000000000018              unused
```

By the definition of RTLD_LAZY only variables (objects) would be loaded eagerly.
Please read in the definition "Lazy binding is performed only for function references".
My suspicion is that dynamic loader should not be loading any function marked symbols in case you are doing a RTLD_LAZY dlopen.

**Comment by VVIsaev** [comment] 2021-02-26 13:09
Just for clarification: issue filed not about relocation, but about `RTLD_LAZY` flag which does not work properly.

I mentioned relocation only because this is obvious difference between arcv2 and arcv3 binaries. This does not mean that I pointed to relocation as an issue here.

**Comment by vineetgarc** [comment] 2021-02-26 16:20
> It is unclear to me why we need to be placing functions in PLT in the first place.

External Function calls are always routed through PLT.

> Also in case you place functions in PLT there is no actual difference in between RTLD_LAZY and RTLD_NOW, and for this reason the test itself looks at least a little "stupid".

No that's totally incorrect. GOT relocations are always processed eagerly. PLT relocations are by default done lazily unless BIND_NOW / RTLD_NOW is used.

> The conclusion to take might be: We either are not differentiating Variable from Function symbols properly in the binary, or there is some problem in the dynamic loader that is not differentiating between Variable and Function symbols when resolving them.

Also incorrect. ldso doesn't know/care (for most part) if a symbol is a function or data. The relocation types tell it what to so. If it is in GOT it will be processed right away - which is what is happening here.

**Comment by vineetgarc** [comment] 2021-02-26 16:23
> Let me explain the issue here.
> `foo()` is not defined, so in case of usual linking we should have this `undefined symbol` error.
> 
> But there is a flag `RTDL_LAZY` for `dlopen()`, which should perform lazy binding. From [man dlopen](https://man7.org/linux/man-pages/man3/dlopen.3.html):
> 
> ```
>        RTLD_LAZY
>               Perform lazy binding.  Resolve symbols only as the code
>               that references them is executed.  If the symbol is never
>               referenced, then it is never resolved.  (Lazy binding is
>               performed only for function references; references to
>               variables are always immediately bound when the shared
>               object is loaded.)  Since glibc 2.1.1, this flag is
>               overridden by the effect of the LD_BIND_NOW environment
>               variable.
> ```
> 
> For example how it works for host gcc:
> 
> ```
> isaev@isaev-7410:tmp$ gcc -fPIC -shared lib.c -o lib.so
> isaev@isaev-7410:tmp$ gcc -ldl main.c -o main
> isaev@isaev-7410:tmp$ LD_LIBRARY_PATH=. ./main
> PASS
> ```

And this is exactly how this works on ARCv2 as well. 

> There is also code in glibc which do this lazy binding, see https://github.com/foss-for-synopsys-dwc-arc-processors/glibc/blob/5754a6aa79d8e990cdabcc3baffa454e1e666677/sysdeps/arc/dl-machine.h#L128 and https://github.com/foss-for-synopsys-dwc-arc-processors/glibc/blob/5754a6aa79d8e990cdabcc3baffa454e1e666677/sysdeps/arc/dl-machine.h#L381 . I don't have understanding about how this actually works internally, but for developer point of view we should perform lazy binding if we provide lazy flag. Not sure where it should be fixed in binutils or in glibc.
> 
> If you don't like my test, please use this one: https://github.com/foss-for-synopsys-dwc-arc-processors/glibc/blob/arc64/elf/resolvfail.c . Currently it fails for ARC64 with `cannot load testobj1.so: undefined symbol foo`.

Tour test is fine. Good to know it is related to specific glibc test.

**Comment by cupertinomiranda** [comment] 2021-02-26 16:42
My bad if I made everyone think that I was shouting or anything like it. I wasn't.
I just don't want any solution to something that seems to me is not a toolchain issue to be classified as such, and be fixed there as a compromise.

If we start compromising by forcing functions to be placed in PLT, to fix issues like this one, we will end up not having so many opportunities to explore and be unable to have more conservative memory models that would allow full address space usage, etc.

Now addressing the problem, I think we should consider to address this issue from the dynamic loader side by identifying which symbols are functions and not relocate them at loading time, maybe creating a new relocation type if needed.
In any case, functions, when using ldl, are recoverd by a dlsym function call. I guess in a lazy load, dlsym should be responsible to relocate the particular function pointer before returning it.

**Comment by vineetgarc** [comment] 2021-02-26 18:19
So this is no so much about defined / undefined symbols, but how arc64 gcc currently generates code for external (non local) function calls.

For default memory model (medium) gcc generates GOT based calls because it pessimistically assumes (incorrectly IMHO) that plt call would be out of range.

```
unused:
	ldl	r0,[pcl,@foo@gotpc]
	jl_s	[r0]
```

For small model it generates the plt call.

```
unused:
	bl	@foo@plt
```
I think -mcmodel=medium should work like the current ARCv2 backend and plt calls should be generated.

**Comment by claziss** [comment] 2021-06-17 12:34
GCC patch: 
- https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/2e3f50d177909e326839aa57003007be240bd54a

Binutils patch:
- https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/ac44384a496b876b6dffb0c1684c23ac79c04094

**Comment by vineetgarc** [comment] 2021-06-23 19:38
Test passes after gcc fix !
```
# LD_LIBRARY_PATH=. ./resolvfail 
# echo $?
0

```

**Closed as completed by vineetgarc** 2021-06-23 19:38 UTC
Labels: bug, component: gcc, component: binutils, arc64, glibc-testsuite
