### ISSUE TITLE
Issue with exporting memory larger than 25MB

### ISSUE THREAD

**Issue by m-aprameya** [foss-for-synopsys-dwc-arc-processors/toolchain#146] opened 2017-12-05 10:34 UTC
Debugging on HAPS using toolchain 2017.09 Eclipse+OpenOCD using custom OpenOCD configuration file. Exporting memory larger than 25MB to Raw Binary Format hangs at 99%. This took approx. 2.5hours. With any memory size less than 25MB exporting usually takes between 45 mins to 1hr45mins (tested for 10MB and 15 MB). Issue also reproducible with exporting memory on EMSK.

**Comment by claziss** [comment] 2021-01-26 12:03
Is this an issue, can we close it?

**Comment by anthony-kolesov** [comment] 2021-01-26 13:34
There is, probably, some performance issue here, but there are no customer  requests to fix this though.

**Comment by abrodkin** [comment] 2021-01-26 14:02
Indeed, I'd close this one because:
1. That's a very unusual corner case and there're other approached to do that same thing on HAPS especially.
2. Reporter has left the company a couple of years ago and so we won't get any details on what was being done, why and if it still makes any sense.
3. If we're up to looking into it we'd need precise instructions for reproduction which are missing in this report.

**Closed as completed by abrodkin** 2021-01-26 14:02 UTC
Labels: bug, component: openocd, deprecated
