### ISSUE TITLE
Bump glibc to the most recent version 2.34

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#409] opened 2021-08-04 14:10 UTC
There's a new glibc  v2.34 released, see https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html.

**Comment by vineetgarc** [comment] 2021-08-04 16:43
Duplicate of #406 
We don't need to do anything specific for existing ARCv2 port

**Closed as completed by vineetgarc** 2021-08-04 16:43 UTC
Labels: enhancement, component: glibc, release notes
