### ISSUE TITLE
ARC64/glibc DL issue when using large addresses

### ISSUE THREAD

**Issue by cupertinomiranda** [foss-for-synopsys-dwc-arc-processors/toolchain#403] opened 2021-07-19 14:37 UTC
Found this problem when debugging QEMU usermode for ARC64.
It reveals itself as a segmentation fault on QEMU. The reality it is an access to invalid memory, due to a problem in dynamic loader.

Culprit code is:
```
static inline uintptr_t
reloc_index (uintptr_t plt0, uintptr_t pltn, size_t size)
{
  uintptr_t idx = pltn - plt0;
...
}
```

Which becomes:
```
│  > 0x400080e04a <_dl_fixup+18>     bmskl   r2,r1,0x1f                                                                                                                                                                                              
│    0x400080e04e <_dl_fixup+22>     ldl.as  r1,[r0,11]                                                                                                                                                                                              
│    0x400080e052 <_dl_fixup+26>     ldl.as  r1,[r1,1]                                                                                                                                                                                               
│    0x400080e056 <_dl_fixup+30>     subl_s  r2,r2,r1
```

bmskl instruction is incorrect and after looking the reason for it to be there we concluded it was because of type of `reloc_arg` argument used in _dl_fixup function, which inlines reloc_offset which also inlines reloc_index.

The reason for the problem is that reloc_arg gets to be of type:
```
typedef uint32_t Elf64_Word;
typedef int32_t Elf64_Sword;
```

Also in dl-runtime.s for _dl_fixup function, one can see (4 bytes argument reloc_arg):
```
        # Parameters:
        #  l                    =`r0`                   (8)
        #  reloc_arg            =`r1`                   (4)
        #  retaddr              =`r2`                   (8)
        #  regs                 =`r3`                   (8)
        #  framesizep           =`r4`                   (8)
```

I include dl-runtime.i and dl-runtime.s for reference.

[dl-rutime-files.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/6841772/dl-rutime-files.tar.gz)

**Comment by vineetgarc** [comment] 2021-07-19 18:24
I've suggested following fix to Vladimir:

```diff
diff --git a/elf/dl-runtime.c b/elf/dl-runtime.c
index 85a229f6f019..d49657a0287d 100644
--- a/elf/dl-runtime.c
+++ b/elf/dl-runtime.c
@@ -56,7 +56,7 @@ _dl_fixup (
 # ifdef ELF_MACHINE_RUNTIME_FIXUP_ARGS
           ELF_MACHINE_RUNTIME_FIXUP_ARGS,
 # endif
-          struct link_map *l, ElfW(Word) reloc_arg)
+          struct link_map *l, uintptr_t reloc_arg)
```

And since he did the investigation, I've asked him to spin this as patch and propose on glibc mailing list. This is mainline code change which affects all arches, but seems DTRT to me.

**Comment by cupertinomiranda** [comment] 2021-07-19 18:40
Hi Vineet,

Actually both of us did investigate the same in parallel without knowing, me in the context of merging linux usermode in arc64 branch and grab results for that branch.
I would not think it is a good idea to apply this fix to our arc64 reported results based on such a fix.
This fix might hide the fundamental problem in the arc64 port of glibc, please don't let this hang for long time.

Regards,
Cupertino

**Comment by VVIsaev** [comment] 2021-07-19 18:55
Hi there,

Yeah, I'm looking into it without filing bug, sorry about that.

I don't think that we should apply this fix to our glibc without maintainers review, but we can temporally move qemu-user to lower 32 bit (as we done for kernel), so we will have configuration match between kernel and qemu-user and can start using it. What do you think, @cupertinomiranda ?

Thank you,
Vladimir Isaev

**Comment by vineetgarc** [comment] 2021-07-19 19:51
> I don't think that we should apply this fix to our glibc without maintainers review,

Seriously. So you want a jury's blessings for an obvious problem and fix.
First of the all the problem is not even captured correctly (and yet again we are working on a problem BEFORE filing for a issue)

To resolve a lazy binding, resolver _dl_runtime_resolve() calls _dl_fixup() whose 2nd argument is the address of PLT entry which needs to be fixed up. This address obviously needs to be 64-bit which is correctly setup by caller in register r1.

```
ENTRY (_dl_runtime_resolve)
...
	MOVR 	r1, r12          <--- 64-bit MOVL: address of PLT entry
	bl.d  	_dl_fixup
	MOVR   	r0, r11
```

However _dl_fixup() is common code for all arches and it uses ELF64_Word for 2nd argument, which confusingly maps to a 32-bit value.

```
typedef uint32_t Elf64_Word;
Elf64_Addr  __attribute ((noinline)) _dl_fixup (   struct link_map *l, Elf64_Word reloc_arg)
{
   Elf64_Rela *const reloc  = ((l)->l_info[23]->d_un.d_ptr+ reloc_offset (pltgot, reloc_arg));
```

Thus the value is truncated to 32-bits when it is passed to reloc_offset() which is THE bug we are seeing. The obvious fix is to define reloc_arg as uintptr which works fine for both 32-bit and 64-bit. So this is NOT a quick hack but the real fix. I don't think why we are so overly cautious about this harmless/localized change. Sure it is cross-arch and upstream might  want us to do something else, but there is nothing wrong in doing this in our arc64 port.

**Comment by vineetgarc** [comment] 2021-07-19 19:59
@VVIsaev the fix is pushed to arc64, if you are game, submit it to glibc mailing list or else let me know and i'll do it.

**Comment by vineetgarc** [comment] 2021-07-19 20:01
> we can temporally move qemu-user to lower 32 bit (as we done for kernel), so we will have configuration match between kernel and qemu-user and can start using it. What do you think, @cupertinomiranda ? 

I'd say quite the opposite. This might be the least risky way to actually test out codegen/linking beyond 32-bit and flush out any compiler, simulator issues to begin with.

**Comment by cupertinomiranda** [comment] 2021-07-19 21:35
@VVIsaev  My opinion is that, anyone individually can have any compromises as they wish, but keep them private and don't make it part of the main branch.
Please don't hide the problem neither in glibc or qemu, try to debug and address it in a proper way ASAP.

**Comment by vineetgarc** [comment] 2021-07-19 22:05
> @VVIsaev My opinion is that, anyone individually can have any compromises as they wish, but keep them private and don't make it part of the main branch.
> Please don't hide the problem neither in glibc or qemu, try to debug and address it in a proper way ASAP.

What part of this is non-comprehensible to you. I'm the glibc maintainer and there is no hiding or papering, that is the bug fix. It WILL be part of main branch - and already is !

**Comment by cupertinomiranda** [comment] 2021-07-19 22:21
Seriously, I don't understand in what tone you read my messages ... I was just replying to @VVIsaev only and my perception was, when I chat with him earlier, that it was sort of a temporary solution in GLibC.

**Comment by cupertinomiranda** [comment] 2021-07-19 22:34
Without wanting to aggravate the situation, I noticed that x86_64 does not set the relative offset in .got.plt but rather the linker patches the entry with the index of the refered plt entry.
Don't know how easy it would be to change it in the linker thought. There is some very small performance benefit but it would imply to change the ABI. Don't know if Metaware has anything to do with the topic.

Please notice the comment in `sysdeps/x86_64/dl-runtime.h`.

 ```
 /* The ABI calls for the PLT stubs to pass the index of the relocation
   and not its offset.  In _dl_profile_fixup and _dl_call_pltexit we
   also use the index.  Therefore it is wasteful to compute the offset
   in the trampoline just to reverse the operation immediately
   afterwards.  */
static inline uintptr_t
reloc_offset (uintptr_t plt0, uintptr_t pltn)
{
  return pltn * sizeof (ElfW(Rela));
}

static inline uintptr_t
reloc_index (uintptr_t plt0, uintptr_t pltn, size_t size)
{
  return pltn;
}
```

**Closed as completed** 2021-07-21 17:15 UTC
