### ISSUE TITLE
Issue with R_ARC_TLS_TPOFF relocation

### ISSUE THREAD

**Issue by pavelvkozlov** [foss-for-synopsys-dwc-arc-processors/toolchain#476] opened 2022-09-12 08:37 UTC
With one of uclibc tests I faced an issue with **R_ARC_TLS_TPOFF** relocation.

The test explicitly uses ```TLS_IE()``` macros to generate R_ARC_TLS_TPOFF relocation:
``` c
#include <stdio.h>

#define TLS_IE(x)             \
  ({ void *__result;            \
    void *tp = __builtin_thread_pointer();      \
    __asm__ ("ld %0, [pcl, @" #x "@tlsie]   \n"   \
        "add %0, %1, %0               \n"         \
        : "=&r" (__result) : "r" (tp));   \
      __result; })

__thread int foo, bar, moo;

int main(int argc, char *argv[])
{
	int *fp, *bp, *mp;

	foo = 5; bar = 7;  moo = 9;
	printf("foo addr = %p val = %d\n", &foo, foo);
	printf("bar addr = %p val = %d\n", &bar, bar);
	printf("moo addr = %p val = %d\n", &moo, moo);

	fp = TLS_IE (foo);  bp = TLS_IE (bar); mp = TLS_IE (moo);
	printf("IE: foo addr = %p val = %d\n", fp, *fp);
	printf("IE: bar addr = %p val = %d\n", bp, *bp);
	printf("IE: moo addr = %p val = %d\n", mp, *mp);

	return 0;
}
```
Test result output:
```
foo addr = 0x201477a8 val = 5
bar addr = 0x201477ac val = 7
moo addr = 0x201477b0 val = 9
IE: foo addr = 0x201477a8 val = 5
IE: bar addr = 0x201477b0 val = 9
IE: moo addr = 0x201477b8 val = 538187244
```

```bar@tlsie``` resolves 4 bytes after the correct address, and ```moo@tlsie``` resolves 8 bytes after.
[readelf output](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/9545703/tst-tls-readelf.txt)
The linker adds extra addend:
```
00001ff4  00000b44 R_ARC_TLS_TPOFF   00000000   foo + 0
00001ff8  00000944 R_ARC_TLS_TPOFF   00000004   bar + 4
00001ffc  00000a44 R_ARC_TLS_TPOFF   00000008   moo + 8
```
In a separate test, I defined local thread variables in a shared library and used them in a program, to get
R_ARC_TLS_TPOFF relocation, in this case, relocation appears without extra addend and all is ok. 
Also this issue reproduces with glibc. May be it is a known issue and using ```TLS_IE``` macros in such manner is incorrect or something wrong with relocation?

**Comment by claziss** [comment] 2022-09-12 11:41
It looks that u use the glibc toolchain instead of uclibc toolchain, as far as I can see from your reader elf output.
```
Version needs section '.gnu.version_r' contains 1 entry:
 Addr: 0x0000000000000410  Offset: 0x000410  Link: 6 (.dynstr)
  000000: Version: 1  File: libc.so.6  Cnt: 2
  0x0010:   Name: GLIBC_2.32  Flags: none  Version: 3
  0x0020:   Name: GLIBC_2.34  Flags: none  Version: 2
```

**Comment by pavelvkozlov** [comment] 2022-09-12 11:56
This issue reproducers with uclibc and with glibc, yes, this readelf can be from my last configuration with glibc, sorry. 
[readelf output](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/9547693/tst-tls-uclibc-readelf.txt) for the test built with uclibc environment.

**Comment by claziss** [comment] 2022-09-12 17:51
Can u tell me what compiler options are u using for your experiment?

**Comment by pavelvkozlov** [comment] 2022-09-13 08:43
Under buildroot, the original test builds with the following options:
```
arc32-buildroot-linux-uclibc-gcc -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g0 -Wl,-z,max-page-size=4096 -I../../test -D_GNU_SOURCE -Wno-missing-field-initializers -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g0 -Wl,-z,max-page-size=4096 -DUSE_TLS=1 -DHAVE___THREAD=1 -I. -DHAVE_TLS_MODEL_ATTRIBUTE=1    -c tst-tls1.c -o tst-tls1.o

arc32-buildroot-linux-uclibc-gcc  tst-tls1.o -o tst-tls1
```
Test source from the first message I've built without any special options (used toolchain generated by buildroot):
```
arc32-linux-cc -v -o tst-tls tst-tls.c -Wl,-v
```
Extra output with compiler configuration options and linker options in the file [arc32-linux-cc.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/9554862/arc32-linux-cc.txt)


Test with shared library I've built with following options:
```
Library:
arc32-linux-cc -c -fPIC -o tmod.o tmod.c -I.
arc32-linux-cc -shared -o libtmod.so tmod.o 
Test:
arc32-linux-cc -o tst-tls-dyn tst-tls-dyn.c -I. -L. -Wl,-v -l tmod
```
For my experiments I used buildroot from **arc64** branch with toolchain generated by buildroot( binutils 2.38.50.20220215, gcc 12.1.1 20220615), also I've tried builroot from **arc64-2021.11.x** branch ( binutils 2.34 and gcc 10.2.0), the test result was the same.

**Comment by claziss** [comment] 2022-09-21 15:21
I am sorry, I cannot reproduce your issue. Readelf reports this to me:
```
00013ff0  00000344 R_ARC_TLS_TPOFF   00000000   foo + 0
00013ff4  00000144 R_ARC_TLS_TPOFF   00000004   bar + 0
00013ff8  00000244 R_ARC_TLS_TPOFF   00000008   moo + 0
```

Maybe this commit may fix your issue: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/41664c7cd47feea6be8cc8f72d92a96e57c48d5b

EDIT: the above relocs are dynamic, hence they need to be fixed correctly by the OS dynamic linker.

**Comment by pavelvkozlov** [comment] 2022-09-22 09:04
Hi @claziss,

I can confirm, the issue is gone after the commit https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/commit/41664c7cd47feea6be8cc8f72d92a96e57c48d5b

**Comment by claziss** [comment] 2022-09-22 10:04
Thanks for your report. Closing this one now.

**Closed as completed by claziss** 2022-09-22 10:04 UTC
Labels: bug, component: binutils, component: glibc, component: uclibc
