### ISSUE TITLE
Compiling 2016.03 with no NPTL support

### ISSUE THREAD

**Issue by ekromskoy** [foss-for-synopsys-dwc-arc-processors/toolchain#126] opened 2017-06-20 21:08 UTC
Hi,

I am trying to compile 2016.03 release of ARC toolchain with --no-ntpl build option. It fails with this error in log file: 

/tmp/ccz6wTrY.s: Assembler messages:
/tmp/ccz6wTrY.s:15: Error: invalid operands (.bss and .text sections) for `-'
/tmp/ccz6wTrY.s:15: Error: invalid operands (.text and *ABS* sections) for `&'
/tmp/ccz6wTrY.s:17: Error: invalid operands (.text.exit and .text sections) for `-'
/tmp/ccz6wTrY.s:17: Error: invalid operands (.text and *ABS* sections) for `&'
./ldso/ldso/arc/dl-sysdep.h:156: Error: invalid operands (.text and *ABS* sections) for `&'
make: *** [ldso/ldso/ldso.oS] Error 1

I believe there was no changes to dl-sysdep.h file since 2015.12 release yet I can compile 2015.12 with no ntpl and cannot 2016.03 release.

How can I fix this compilation error? 

Second question is regarding NPTL with uClibc. I want to disable NPTL because simple test application linked with libpthread when compiled statically would segfault when certain number of threads created. I don't see this problem when use dynamic linking with libpthread.so. And when I compile toolchain with --no-nptl option there is no problem at all either statically or dynamically linking with libpthread. Might be it is a know implementation issue and there is some elegant solution to NTPL instead of throwing it away? This is old issue with ARC toolchain and historically we just had NPTL not enabled.   

Thank you,
Ed

**Comment by claziss** [comment] 2017-06-20 21:27
I think this op is not any longer valid:
```asm
add %0, pcl, _dl_start-.+(.&2) ;runtime addr of _dl_start
```
now you can use this:
```asm
add %0, pcl, _dl_start@pcl     ;runtime addr of _DYNAMIC
```

**Comment by ekromskoy** [comment] 2017-06-20 21:54
If I just change that line in uClibc/ldso/ldso/arc/dl-sysdep.h file I still getting error:
/tmp/ccPlCwrm.s: Assembler messages:
/tmp/ccPlCwrm.s:15: Error: invalid operands (.bss and .text sections) for `-'
/tmp/ccPlCwrm.s:15: Error: invalid operands (.text and *ABS* sections) for `&'
/tmp/ccPlCwrm.s:17: Error: invalid operands (.text.exit and .text sections) for `-'
/tmp/ccPlCwrm.s:17: Error: invalid operands (.text and *ABS* sections) for `&'
make: *** [ldso/ldso/ldso.oS] Error 1

Might be some other place..

**Comment by claziss** [comment] 2017-06-20 22:01
The best is to see exactly what it goes wrong in which file. Please use -save-regs option for the compiler to obtain the faulty file.

**Comment by ekromskoy** [comment] 2017-06-20 22:10
dl-startup.h has similar fanny asm math for no NPTL. I fixed it in similar fashion; now will see if it will work. Thank you,
Ed

**Comment by claziss** [comment] 2017-06-20 22:11
I will ask Vineet to comment on this, it is his code and he may have different inputs for you.

**Comment by ekromskoy** [comment] 2017-06-20 22:11
Thanks again

**Comment by vineetgarc** [comment] 2017-06-20 23:08
So first things first: starting with GNU 2016.03 when NPTL was first officially supported - we stopped testing (hence supporting) the LT.old threading library. So even if you somehow made it work we won't be able to support you on it. We are ready to help you on any issues related to NPTL though.

About your comment
> I want to disable NPTL because simple test application linked with libpthread when compiled 
> statically would segfault when certain number of threads created. I don't see this problem when
> use dynamic linking with libpthread.so.

You mean you see these errors with your application built with 2016.03 built today ?

In the past, I have fixed a bunch of static linking issues in generic uClibc code (which have long since been merged usptream) - perhaps your experience is from that time.

So would suggest you to
(1) go back to NPTL toolchain build of 2016.03
(2) retest whatever your test case was - dynamic or static and let us know if it fails etc

-Vineet

**Comment by vineetgarc** [comment] 2017-06-20 23:20
BTW any specific reason you are picking up GNU 2016.03 when there's already GNU 2017.03 released in recent times. It has a more modern gcc 6.x compiler and many more bug fixes in binutils/uClibc etc

**Comment by ekromskoy** [comment] 2017-06-21 18:22
Toolchain will be part of SDK release and Linux kernel for our SoC we currently support is 3.12. That's the reason I am staying with gcc 4.8.

NPTL used to be better, even though not officially supported, in 2015.12 release with NPTL I could create up to 127 threads (plus main one). With 2016.03  segmentation fault happens when I create 6 threads. 

Below is test example:
```c
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

/*
 *	th:
 *		Just create a bunch of threads.
 *
 *	Usage:
 *		th n
 *
 *		n	- number of thread to run (1-500)
 *
 *	Description:
 *		Just create threads as fast as possible.  Each thread
 *	prints its thread number and waits for a join.
 *     Makefile:
 *     th:
 *    	arc-linux-gcc -Wall -fverbose-asm -save-temps -static -oth th.c -lpthread
 *	arc-linux-gcc -Wall -othread th.c -lpthread
 */

static void *thread( void* );
static pthread_mutex_t mux = PTHREAD_MUTEX_INITIALIZER;


/*
 *	main:
 */

int
main( int argc, char **argv )
	{
	pthread_t *tids;
	int *tn, n, i;

	if( argc != 2 )
		{
		printf( "Usage: %s n\n", argv[0] );
		exit(1);
		}

	n = atoi( argv[1] );
	if( n<1 || n>500 )
		{
		printf( "Invalid number of threads (1-500)\n" );
		exit(1);
		}

	printf("creat %d posix threads and then terminating them all.\n", n);

	tids = (pthread_t*) malloc( n * sizeof(pthread_t) );
	tn = (int*) malloc( n * sizeof(int) );
	if (!tn || !tids)
		{
		perror("malloc:");
		exit(2);
		}


	for( i=0; i<n; i++ )
		{
		tn[i] = i + 1;
		pthread_create( &tids[i], NULL, thread, &tn[i] );
		}

	for( i=0; i<n; i++ )
		pthread_join( tids[i], NULL );

	return 0;
	}


/*
 *	thread:
 *		Just print the given thread number and return.
 */

static void *
thread( void *arg )
	{
	int *n;

	n = (int*) arg;
	pthread_mutex_lock(&mux);
	printf( "thread %d\n", *n );
	pthread_mutex_unlock(&mux);

	return NULL;
	}
```
On ARC target platform

# ./th 6
creat 6 posix threads and then terminating them all.
thread 6
thread 5
thread 4
thread 3
thread 2
thread 1
Segmentation fault
# ./th 5
creat 5 posix threads and then terminating them all.
thread 5
thread 4
thread 3
thread 2
thread 1
# ./thread 10
creat 10 posix threads and then terminating them all.
thread 1
thread 8
thread 9
thread 10
thread 7
thread 6
thread 5
thread 4
thread 3
thread 2
#

**Comment by vineetgarc** [comment] 2017-06-21 19:28
3.12 kernel as it is doesn't impose any requirement for gcc 4.8.
I could boot the 3.12 with gcc 6.3 on nsim !

> [ARCLinux]# dmesg | head -n 5
> Linux version 3.12.74 (vineetg@vineetg-Latitude-E7450) (gcc version 6.3.0 (ARCompact ISA Linux
> uClibc toolchain 2017.03) ) #5 PREEMPT Wed Jun 21 12:07:46 PDT 2017
> Board "arc-angel4" from snps (Manufacturer)

**Comment by vineetgarc** [comment] 2017-06-21 19:37
The reason being supporting you on current tools release will be much more quicker !

**Comment by ekromskoy** [comment] 2017-06-21 20:10
Did you change EF_ARC_OSABI_CURRENT to be 0x0400? We plan to move to gcc6.x branch once we move our kernel to something more recent. Beside of kernel we have quite ancient u-boot which cannot be compiled by new 6.x gcc and who knows what else. Actually 2016.13 with LT seems to be OK. NPTL has some problems and in embedded world some customers do use static linking.

**Comment by vineetgarc** [comment] 2017-06-22 01:29
As I mentioned in #120, stable backport for ABI change was rejected by GKH. And turns out it is not a hard requirement [so v3.12 kernel (v3) work fine with latest userspace (v4)] given that the abi check in older kernels allows that combination (and technically for arc700 builds, v3 and v4 are code compatible - they only differ for ARC HS generated code).

Your usage of static linking is not really a issue, I understand that embedded folks with smaller systems could use it.
But supporting LT.old on 2016.03 would be problem, we could rather focus on fixing any NPTL and related issues - someone here is already on to reproducing your test case above.

BTW just curious what ARC SoC is all this for (you could reply to me privately @ vgupta@synopsys.com if you so wish )

**Comment by vineetgarc** [comment] 2017-06-22 18:12
FWIW, example works great with 2017.03 for both static and dynamic linking

$ for i in 1 2 3 4 5 6 7 8 9 10; do ./th-static $i; done
$ for i in 1 2 3 4 5 6 7 8 9 10; do ./th-dyn $i; done

**Comment by ekromskoy** [comment] 2017-06-22 18:35
It worked for small numbers of threads with 2015.12 too. With 2015.12 to get segmentation fault I had to run
$ ./th-static 127

**Comment by vineetgarc** [comment] 2017-06-22 18:51
[ARCLinux]# ./th-static 256
creat 256 posix threads and then terminating them all.
thread 1
thread 2
thread 3
...
thread 256
thread 236
thread 249
thread 237
thread 241
thread 234
thread 233
thread 232
thread 231
[ARCLinux]#

**Comment by vineetgarc** [comment] 2017-06-22 19:10
But hold on - NPTL requirs an atomic cmpxchg primitive, which as of GNU 2016.03 only has a LLOCK/SCOND based implementation which your SoC lacks. So how can you possibly be running such a userspace without out of tree changes to uClibc.

**Comment by ekromskoy** [comment] 2017-06-22 19:58
We do have change addressing that. I guess dynamic library wouldn't work either.

**Comment by ekromskoy** [comment] 2017-06-26 20:15
Now I have other problem. 

Compiling rootfs (using buildroot) and linux kernel using rootfs as initramfs; everything is OK except one thing: any app compiled static works as expected and any app (same code) compiled dynamic has no output. It looks like they start and immediately exit with no any output.

I didn't have this problem with previous 2015.12 and older toolchains.

**Comment by vineetgarc** [comment] 2017-06-27 08:26
I;m not sure what your detailed config is, here 2016.03 based dynamic linked system just boots/runs fine !

**Comment by ekromskoy** [comment] 2017-06-27 14:29
Hi Vineet,

Ok, the problem is with no-nptl option and ldso. Could you be more specific why do you have conditional #ifdef compilation and for NPTL case use _DYNAMIC symbol and for no-nptl case you keep using _dl_start? What is the proper way? Can I keep _DYNAMIC for no-nptl case as well? Currently I found that elf_machine_dynamic() returns address of _DYNAMIC for both NPTL and no-nptl cases which is likely wrong.

**Comment by vineetgarc** [comment] 2017-06-27 14:57
Hi Ed,

We didn't test no-nptl with 2016.03 - LT.old has a lot of fundamental design hacks and kludges which didn't make sense to support when the rest of tooling supported TLS (Thread Local Storage) and thus NPTL was enabled.

About your question for _DYNAMIC and #ifdef, the idea was to identify the new gcc (with TLS support) vs. the old - since the newer gcc had issue with parsing the awkward assembler constructs such as 
    "   add     r12, pcl, _dl_skip_args-.+(.&2)                 \n"

This was done in an implicit way - we simply used the uClibc NPTL build flag to "infer" the presence of new gcc.

**Comment by ekromskoy** [comment] 2017-06-27 16:08
Ok, thank you. _DYNAMIC should be used for both NPTL and LT.old. Seems to work now. As I said before the only reason I use LT.old because our core/bus don't support atomic compare and exchange. At this time I disabled atomic compare and exchange instruction for every bit width in  uClibc/libc/sysdeps/linux/arc/bits/atomic.h
and had to modify __cxa_finalize() in uClibc/libc/stdlib/_atexit.c to use __UCLIBC_MUTEX_LOCK(__atexit_lock) in same fashion as rest of functions there do instead of using atomic compare and exchange.

EX on cached memory region seems to work; but should be no other access there invalidating cache. Probably this is what LT.old use.

**Comment by vineetgarc** [comment] 2019-09-24 00:41
uClibc LT.old is not tested/supported. Closing this one !

**Closed as completed by vineetgarc** 2019-09-24 00:41 UTC
Labels: deprecated
