### ISSUE TITLE
Problem building toolchain

### ISSUE THREAD

**Issue by nandub** [foss-for-synopsys-dwc-arc-processors/toolchain#36] opened 2013-12-13 05:29 UTC
I was able to change some of the scripts to be able to run this on Mac OS X, but after running for a long while it fails with this error:

```
./build-all.sh --no-uclibc --elf32 --install-dir /opt/toolchains
Checking out GIT trees ...
Downloading external dependencies...
Linking unified tree ...
START ELF32: Thu Dec 12 21:49:17 CST 2013
Installing in /opt/toolchains
Configuring tools ...
  finished configuring tools
Building tools ...
ERROR: tools build failed.
ERROR: arc-elf32- tool chain build failed.
./build-all.sh --no-uclibc --elf32 --install-dir /opt/toolchains  2543.22s user 1012.95s system 79% cpu 1:14:25.96 total
```

Where is the build logs files? here ../log-4.8/*.log??

**Comment by anthony-kolesov** [comment] 2013-12-13 05:48
Yes, logs are in ../logs-4.8/elf-build-%datetime%.log. Or you can edit build-elf.sh and remove redirection of Make stdout/err to the logfile.

**Comment by nandub** [comment] 2013-12-13 07:12
Thanks, I rerun again it took a while but now I can see the errors:

The last few lines is displayed below

```
duplicate symbol _SUBOFHI in:
    libsim.a(cpu5.o)
    libsim.a(mloop7.o)
duplicate symbol _ADDCQI in:
    libsim.a(cpu5.o)
    libsim.a(mloop7.o)
duplicate symbol _ADDCFQI in:
    libsim.a(cpu5.o)
    libsim.a(mloop7.o)
duplicate symbol _ADDOFQI in:
    libsim.a(cpu5.o)
    libsim.a(mloop7.o)
duplicate symbol _SUBCQI in:
    libsim.a(cpu5.o)
    libsim.a(mloop7.o)
duplicate symbol _SUBCFQI in:
    libsim.a(cpu5.o)
    libsim.a(mloop7.o)
duplicate symbol _SUBOFQI in:
    libsim.a(cpu5.o)
    libsim.a(mloop7.o)
duplicate symbol _sim_addr_range_hit_p in:
    nrun.o
    libsim.a(traps.o)
duplicate symbol _sim_addr_range_hit_p in:
    nrun.o
    libsim.a(devices.o)
ld: 696 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [run] Error 1
make[1]: *** [all] Error 1
make: *** [all-sim] Error 2
```

**Comment by anthony-kolesov** [comment] 2013-12-13 07:33
Try building with option --no-sim:

```
./build-all.sh --no-uclibc --elf32 --install-dir /opt/toolchains --no-sim
```

That will disable CGEN simulator, which causes problems here. We know that CGEN cannot be built on Windows and disable it there by default. Probably the same for Mac... Or maybe this is caused by Clang.

**Comment by anthony-kolesov** [comment] 2013-12-13 07:38
Also when you rerun pass those options:

```
--no-unisrc --no-auto-pull --no-auto-checkout
```

With those build script will no do operations that should be done only once: building unified source tree (very time costly) and updating Git repositories

**Comment by nandub** [comment] 2013-12-14 20:28
Thanks, I used the `--no-sim` parameter to get past the error.  Right now I rerunning it again with `--no-pdf` as the pdf portion failed as well.

**Comment by nandub** [comment] 2013-12-14 21:04
I have successfully built an arc-elf32 toolchain on my Mac OS X Mountain Lion (10.8.5) I used the following:

`./build-all.sh --no-uclibc --elf32 --install-dir /opt/toolchains --no-sim --no-pdf --no-unisrc --no-auto-pull --no-auto-checkout`

```
gcc (ARCompact elf32 toolchain (built 20131214)) 4.8.0
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by anthony-kolesov** [comment] 2013-12-24 13:37
I suppose this issue has been resolved, so I'm closing it. Let us of any problems.

**Closed as completed by anthony-kolesov** 2013-12-24 13:37 UTC
Labels: question

**Comment by nandub** [comment] 2013-12-24 22:08
Yes, thanks
